apiVersion: v2
name: bk-user
description: A Helm chart for bk-user
type: application
version: 1.1.2
appVersion: v2.3.1

dependencies:

- name: mariadb
  version: "9.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: mariadb.enabled

- name: redis
  version: "14.x.x"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
