global:
  sharedDomain: "bktencent.example.com"
  # 全局 registry
  sharedImageRegistry: "ccr.ccs.tencentyun.com/bk.io"
  env:
    BK_PAAS_HOST: ""

bkuserapi:
  enabeld: true
  env:
    # !!!请修改初始账号密码!!!
    INITIAL_ADMIN_USERNAME: "admin"
    INITIAL_ADMIN_PASSWORD: "Blueking@2019"
  # 挂载内建 DB 变量
  envFrom:
    - configMapRef:
        name: bk-user-api-mariadb-env
    - configMapRef:
        name: bk-user-api-redis-env

bkusersaas:
  enabled: true
  # 挂载内建 DB 变量
  envFrom:
    - configMapRef:
        name: bk-user-saas-mariadb-env

mariadb:
  enabled: true
  commonAnnotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-failed,before-hook-creation
  architecture: standalone
  auth:
    username: "bk-user"
    password: "maybe_a_strong_passwd"
  primary:
    # 默认我们未开启持久化，如有需求可以参考:
    # - https://kubernetes.io/docs/user-guide/persistent-volumes/
    # - https://github.com/bitnami/charts/blob/master/bitnami/mariadb/values.yaml#L360
    persistence:
      enabled: false
  initdbScriptsConfigMap: "bk-user-mariadb-init"

redis:
  enabled: true
  commonAnnotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-failed,before-hook-creation
  sentinel:
    enabled: false
  auth:
    password: "maybe_another_strong_passwd"
  persistence:
    enabled: false