apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-user-api-redis-env
  labels:
    {{- include "bk-user.labels" . | nindent 4 }}
data:
  {{- if .Values.redis.enabled }}
  {{- $redis_url := printf "redis://:%s@%s-redis-master:%s/0" .Values.redis.auth.password .Release.Name (.Values.redis.master.service.port | toString )}}
  CELERY_BROKER_URL: {{ $redis_url }}
  CELERY_RESULT_BACKEND: {{ $redis_url }}
  {{- else -}}
  {{- $redis_url := printf "redis://:%s@%s-redis-master:%s/0" .Values.api.externalRedis.default.password .Release.Name (.Values.api.externalRedis.default.port | toString )}}
  CELERY_BROKER_URL: {{ $redis_url }}
  CELERY_RESULT_BACKEND: {{ $redis_url }}
  {{- end -}}
