{{- $namePrefix := include "chartty.name" . -}}
{{- $enabled := default false .Values.global.imageCredentials.enabled -}}
{{- if $enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $namePrefix }}-{{ .Values.global.imageCredentials.name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "chartty.dockerconfigjson" . }}
{{- end }}
