[tool.black]
line-length = 119
skip-string-normalization = 'true'
# ignore example
# exclude = '''
# /(
#   | .+/migrations
# )/
# '''

[tool.isort]
multi_line_output = 3
include_trailing_comma = 'true'
force_grid_wrap = 0
use_parentheses = 'true'
line_length = 119
# ignore example
# skip_glob = ["*/migrations/**", "*/sdk/**", "*/node_modules/**"]

[tool.flake8]
ignore = "C901,E203,W503"
max-line-length = 119
max-complexity = 12
format = "pylint"
# ignore example
# exclude = "*migrations*,*.pyc,.git,__pycache__,*/node_modules/*,*/templates_module*,*/bin/*,*/config/*,*sdk*"

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
strict_optional=false
pretty=true

# if you want to ignore migrations/* 
# [[tool.mypy.overrides]]
# module = ["*.migrations.*"]
# ignore_errors = true