{{- if .Values.mariadb.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-user-mariadb-init
  labels:
    {{- include "chartty.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `{{ .Values.api.defaultDBName }}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    CREATE DATABASE IF NOT EXISTS `{{ .Values.saas.defaultDBName }}` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    GRANT ALL PRIVILEGES ON `{{ .Values.api.defaultDBName }}`.* TO `{{ .Values.mariadb.auth.username }}`@'%';
    GRANT ALL PRIVILEGES ON `{{ .Values.saas.defaultDBName }}`.* TO `{{ .Values.mariadb.auth.username }}`@'%';
{{- end -}}