apiVersion: v1
kind: ConfigMap
metadata:
  name: bk-user-api-mariadb-env
  labels:
    {{- include "chartty.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  {{- if .Values.mariadb.enabled }}
  DB_NAME: "{{ .Values.api.database.preferName }}"
  DB_USER: "{{ .Values.mariadb.auth.username }}"
  DB_PASSWORD: "{{ .Values.mariadb.auth.password }}"
  DB_HOST: "{{ .Release.Name }}-mariadb"
  DB_PORT: "3306"
  {{- end -}}