{{- $global := . }}
{{- $namePrefix := include "chartty.name" . -}}
{{- range $map := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $namePrefix }}-{{ $map.name }}
  labels:
    {{- include "chartty.labels" $global | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
data:
  {{- range $file := $map.files }}
    {{ $file.name }}: |-
      {{- if eq (default "plain" $file.format) "yaml" }}
        {{- $file.data | toYaml | toString | nindent 6 }}
      {{ else }}
        {{- $file.data | toString | nindent 6 }}
      {{- end }}
  {{- end }}
{{- end }}