{{- $global := . }}
{{- $chartName := include "chartty.name" . -}}
{{- range $processType, $proccesInfo := .Values.processes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chartName }}-{{ $processType }}
  labels:
    process_type: {{ $processType }}
    {{- include "chartty.labels" $global | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    process_type: {{ $processType }}
    {{- include "chartty.selectorLabels" $global | nindent 4 }}
{{- end }}