{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chartty.serviceAccountName" . }} 
  labels:
    {{- include "chartty.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
  {{- end }}
{{- end }}
