{{/* 检查必填环境变量 */}}
{{- define "chartty.envs.check" -}}
{{- if .Values.requiredEnvList -}}

{{- $envs := dict -}}

{{- range $env := fromYamlArray (include "chartty.envs" .) -}}
  {{- if $env.value -}}
  {{- $_ := set $envs $env.name $env.value -}}
  {{- end -}}
{{- end -}}

{{- range $key := .Values.requiredEnvList -}}
{{- $_ := required (printf "env.%s is required" $key) (index $envs $key) -}}
{{- end -}}

{{- end -}}

{{- end }}

{{ $_ := include "chartty.envs.check" . }}